name: 'Template Update Action'
description: 'Check for updates in template files and create a pull request with changes'
inputs:
  config-file:
    description: 'Path to the configuration JSON file'
    required: true
    default: 'config.json'

runs:
  using: 'docker'
  image: 'Dockerfile'
